### ISSUE TITLE
no icon in toolbar, can't import export.tabsaver.json

### ISSUE THREAD

**Issue by The4Apes** [Reeywhaar/tabsaver-2#1]
What a mess...
There is no addon icon for TabSaver2 in the toolbar and i can't import the "export.tabsaver.json" vom TabSaver(1).
Browser: Firefox 133.0.3 (64-Bit)
![tabsaver2](https://github.com/user-attachments/assets/2c30cfe1-258f-4560-b01c-c8a96f5962ee)

**Comment by reeywhaar** [comment]
TabSaver 2 doesn't support data import from TabSaver 1 yet

**Comment by reeywhaar** [comment]
As for icon, not sure if I understood correctly, but icon can be added to toolbar from extensions list
<img width="412" alt="image" src="https://github.com/user-attachments/assets/682c655e-ea66-4791-8fba-e7c8bb2ec5e5" />

**Comment by The4Apes** [comment]
You say TabSaver2 is a continuation of TabSaver1, but it can't import Tabsets from it?
Sounds bad. Very bad. 
But i see, TabSaver2 is not a selective TabSaver, it is a SessionSaver. A SessionSaver is not what I need and definitely not a continuation of TabSaver1. It is a completely different add-on.

**Comment by reeywhaar** [comment]
Well, sorry 🤷‍♂️
